name:                cp2021tStack
version:             0.1.0.0
github:              "githubuser/cp2021tStack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cp2021tStack#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- process
- QuickCheck

library:
  source-dirs: src

executables:
  cp2021tStack-exe:
    main:                cp2021t.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XNPlusKPatterns
    dependencies:
    - cp2021tStack

